### ISSUE TITLE
 tree.compoTestUsingSimulations(verbose=1) - SOLVED

### ISSUE THREAD

**Issue by cymon** [pgfoster/p4-phylogenetics#11]
Part 0: Chi-square = 1132.311982, (dof=1558) P = 1.000000
Composition homogeneity test using simulations.
P-values are shown.

                         Part Num       0      
                        Part Name      all     
---------------------------------    --------  
                    All Sequences   Traceback (most recent call last):
  File "/home/cymon/bin/calculateIfCompostionHomogeneous.py", line 93, in <module>
    main(args.paths, args.input_tree)
  File "/home/cymon/bin/calculateIfCompostionHomogeneous.py", line 56, in main
    do_one_partition(align, align_data, input_tree)
  File "/home/cymon/bin/calculateIfCompostionHomogeneous.py", line 41, in do_one_partition
    tree.compoTestUsingSimulations(nSims=1000, verbose=1)
  File "/usr/local/src/p4-phylogenetics.git.cymon/p4/tree_fit.py", line 1005, in compoTestUsingSimulations
    print(string.center('%6.4f' % partTaps[pNum], partWid), end=' ')
TypeError: float argument required, not list

**Comment by cymon** [comment]
Sorry, not sure what was going on there - but an update to the latest github version cured it...
