### ISSUE TITLE
python 3.10 SystemError

### ISSUE THREAD

**Issue by ssolo** [pgfoster/p4-phylogenetics#17]
There is apparently an issue with python 3.10 .. 
```
~/src/p4-phylogenetics/share/Examples/B_readData/A_readVariousFormats $ p4 foo.1.7.aln
p4> var.alignments[0].composition()
[0.22012578616352202, 0.29245283018867924, 0.31761006289308175, 0.16981132075471697]
p4> Data()
Error pf_newPart: couldn't parse tuple
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/ssolo/src/p4-phylogenetics/p4/data.py", line 81, in __init__
    self._fill(var.alignments)
  File "/Users/ssolo/src/p4-phylogenetics/p4/data.py", line 143, in _fill
    a._initParts()
  File "/Users/ssolo/src/p4-phylogenetics/p4/alignment_part.py", line 69, in _initParts
    aPart.cPart = pf.newPart(len(self.sequences), self.length,
SystemError: PY_SSIZE_T_CLEAN macro must be defined for '#' formats

```

**Comment by pgfoster** [comment]
Indeed it is a breaking change in python 3.10.  I fixed it at the end of June, but neglected to push to github.  Pushed now.  Don't forget to re-make the pfmodule after you pull, possibly using make_pf.sh.
